### ISSUE TITLE
True and false values for is_editor_hint both accepted?

### ISSUE THREAD

**Issue by Loufe** [ItsKorin/Godot-Post-Process-Plugin#12]
![image](https://github.com/ItsKorin/Godot-Post-Process-Plugin/assets/5817861/6fc14157-5d9b-4527-b609-ef46a7171507)

Just wanted to bring this code up, @ItsKorin . I understand if we want to disable in the editor, so the false case (!....) makes sense. Was going to remove the true case but thought I'd ask first if there's a reason why both are included.

**Comment by KorinDev** [comment]
seems like i missed this while reviewing the code, whoops!
i don't really know why is it like that there. but i see you get rid of it in [this](https://github.com/ItsKorin/Godot-Post-Process-Plugin/pull/11/files#diff-3d0271428a36dbacc3fcf0a94c6fd1120d2dad48cbd24bba5fec0349cf1631aa) PR, so il just close this issue
