### ISSUE TITLE
Blur does not seem to work.

### ISSUE THREAD

**Issue by seanj29** [ItsKorin/Godot-Post-Process-Plugin#13]
**Describe the bug**
The "Blur" shader does not seem to do anything

**To Reproduce**
1. Add the post processor node to your project
2. Make a new Resource, or add an existing one with the "Blur" set to any value
3. The shader does not seem to do anything.

**Expected behavior**
Expect some blurring after the shader has been added to the project.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Plugin Version not present in config

**Additional context**
I checked some of the shader code myself and tried it out on a clean copy of the icon, but it seems to not work properly. Maybe because it was originally made for Godot 4? I may be doing something wrong as well.

Also have some separate questions on some of the shader code but not sure where to contact :/

**Comment by KorinDev** [comment]
i'd have to check it ASAP, it's a bit late right now but it hopefully should be fixed by tommorow 04:00 GMT+2, and feel free to contact me on discord, my username is `itzkorin`.

**Comment by KorinDev** [comment]
Update: just checked and Blur works fine in the newest Asset library version (0.0.8) but some (if not most) of the effects seem to not update correctly with the Dynamic Update toggle on or off, after making some changes i noticed some bugs, those are fixed and will be uploaded in the 0.0.9 update which i will release very soon in a day or two

**Comment by seanj29** [comment]
Appreciate it, forgot to mention  but thanks for the plugin as well, it's nice to mess around with and probably going to end up using it or something derivative for VFX for my game

**Comment by KorinDev** [comment]
fixed in v0.0.9.
Asset Library should update at 2024/05/9
Manual version in Releases
