### ISSUE TITLE
Cant ineract with button when i turn on pixelate

### ISSUE THREAD

**Issue by filip293** [ItsKorin/Godot-Post-Process-Plugin#16]
**Describe the bug**
When i turn on pixelate i cant interact with a button and when its off i can, and the mouse isnt capturing when i turn on pixelate.

**To Reproduce**
1. Make a button in 2d
2. Turn on pixelate
3. Try pressing the button (overlay on 3d scene)

**Expected behavior**
 Be able to press the button

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Plugin Version 0.0.9

**Additional context**

**Comment by filip293** [comment]
Fixed the interacting with button part by putting it in a canvas layer
But for the capturing part
I need to go to the taskbar and press the game to make the mouse captured
I mean the mouse does capture even without that, but it doesnt register it.

**Comment by KorinDev** [comment]
i think i know how to fix it, il be fixing it as soon as possible

**Comment by KorinDev** [comment]
Fixed in [v0.1.0](https://github.com/ItsKorin/Godot-Post-Process-Plugin/releases/tag/v0.1.0)
