### ISSUE TITLE
Catching Mouse Movement Error

### ISSUE THREAD

**Issue by AEShooter** [ItsKorin/Godot-Post-Process-Plugin#2]
Whenever I place the post processing node in the scene, I cannot capture the mouse movements on my first person character, but when I delete it, I can capture mouse movements. 
**Here is my mouse movement code:**
```
func _unhandled_input(event):
	if event is InputEventMouseMotion and Input.mouse_mode == Input.MOUSE_MODE_CAPTURED:
		HEAD.rotation_degrees.y -= event.relative.x * mouse_sensitivity
		HEAD.rotation_degrees.x -= event.relative.y * mouse_sensitivity
```

**Comment by AEShooter** [comment]
I tried a lot of ways but nothing fixed, I love the effects and want to advance the code but sorry can't use it :(

**Comment by KorinDev** [comment]
can you tell me what version of the plugin you used?
Thank you

**Comment by AEShooter** [comment]
Sorry for the late reply, I will answer within the day.

19 Mar 2024 Sal 05:53 tarihinde Korin ***@***.***> şunu yazdı:

**Comment by AEShooter** [comment]
I am using v0.0.5, on the Godot Asset Library

**Comment by AEShooter** [comment]
I can't get any error messages, I tried some more things today and still can't find any reason to stop catching mouse movements

**Comment by AEShooter** [comment]
I assume it's about priority issue about hardware or software

**Comment by AEShooter** [comment]
Wow an interesting thing happened, I changed my player's process priority to 1 and it's now catching the movement

**Comment by AEShooter** [comment]
Well it's solved for now but I am stil looking for the reason, tnx
