### ISSUE TITLE
Compatible with 4.3?

### ISSUE THREAD

**Issue by ElementMill** [ItsKorin/Godot-Post-Process-Plugin#26]
Hello, is this working in 4.3? The node isn't appearing for me after installing/restarting.

**Comment by KorinDev** [comment]
Have you enabled the plugin in Project Settings > Addons?

**Comment by ElementMill** [comment]
Wow I did - but checking it again it got turned off. Ah well, works great now - thx!

**Comment by KorinDev** [comment]
No problem!
if you have any problems or suggestions, make sure to tell me, im open for feedback
