### ISSUE TITLE
.gitattribute file missing leading dot

### ISSUE THREAD

**Issue by Gramps** [ItsKorin/Godot-Post-Process-Plugin#5]
Hey there! A user pointed out that the .gitattribute file is missing the leading dot thus the rules aren't being applied to the resulting add-on zip when installing in Godot.  Just wanted to reach out and let you know!

**Comment by KorinDev** [comment]
Hey @Gramps, thanks for pointing it out!
Sorry for taking so long, but i fixed it finally :D

**Comment by Gramps** [comment]
No problem!  Someone pointed it out today somewhat randomly.
